### ISSUE TITLE
I have A ISSUE

### ISSUE THREAD

**Issue by Rodry295** [WerWolv/Tesla-Menu#11]
When I enter the ovl menu I close the game with which I opened it, crashing the atmosphere.

**Comment by TechGeekGamer** [comment]
What error code?

**Comment by Rodry295** [comment]
only with the most recently ovl and tesla , but with the 1.0.4 no.
can be for the edizon ovl; because i close when opened the edizon cheats

**Comment by Rodry295** [comment]
> What error code?

I could not point, immediately delete it and copy the version that worked for me

**Comment by Rodry295** [comment]
> What error code?

i think the tesla`s number

**Comment by Rodry295** [comment]
contents carpet

**Comment by Rodry295** [comment]
the error code is 2001-0520
program 010000000000000d

**Comment by Rodry295** [comment]
responderrr
porfavor

**Comment by TechGeekGamer** [comment]
Maybe ask your question here?  https://discord.gg/qyA38T8
