### ISSUE TITLE
Menu Not Showing In docked mode

### ISSUE THREAD

**Issue by LaunchpadPhil** [WerWolv/Tesla-Menu#13]
The Tesla menu is showing on the Home Screen but not when Im entering a game.
The Menu is still accessible though (Newest Version of The Tesla Menu and Atmosphere 0.12.0 are Installed)

**Comment by HookedBehemoth** [comment]
> This is an issue that started happening in 10.0.0. Go under Settings -> TV Output and make sure that the display scaling is set to 100%. Anything else will cause the menu to not appear anymore in games.

**Comment by LaunchpadPhil** [comment]
ok thank you
