### ISSUE TITLE
Tesla menu is not showing up

### ISSUE THREAD

**Issue by SoyuVitys** [WerWolv/Tesla-Menu#17]
Hi, Recently I tried to install tesla just to use Emuiibo but when I tried to open it, it didn't show up. I tried to restart the console but it still dosn't work. How do I fix it? I installed tesla via Homebrew appstore

**Comment by TechGeekGamer** [comment]
If you are trying to use it while the switch is docked, try opening Tesla in handheld mode.

**Comment by SoyuVitys** [comment]
I already tried it and it doesn't work either

**Comment by kurocygnus** [comment]
I'm having the same problem.

**Comment by masagrator** [comment]
https://github.com/WerWolv/Tesla-Menu/issues/13

**Comment by SoyuVitys** [comment]
The problem of #13 It is not the same as mine

**Comment by masagrator** [comment]
Then describe better your problem. Because for me it looks the same except you didn't specify if it happens in handheld/docked/both.

**Comment by masagrator** [comment]
Have you even installed nx-ovlloader?

**Comment by SoyuVitys** [comment]
yes

**Comment by SoyuVitys** [comment]
I fixed it. I had to reinstall tesla because i deleted some files from it by error. Thanks for the help
