### ISSUE TITLE
fonts are too small with my custom fonts  

### ISSUE THREAD

**Issue by ELY3M** [WerWolv/Tesla-Menu#2]
I happen to use custom fonts in my switch theme. they are fixedsys fonts.   
i will upload both my theme and screenshots.  

![20200220_043827](https://user-images.githubusercontent.com/10571497/74930619-aa4a6b80-53a3-11ea-9085-25576c3c7e00.jpg)
![20200220_043808](https://user-images.githubusercontent.com/10571497/74930623-ab7b9880-53a3-11ea-82d3-6addb3fe9f36.jpg)

[Elys_Theme.zip](https://github.com/WerWolv/Tesla-Menu/files/4230186/Elys_Theme.zip)

**Comment by ELY3M** [comment]
argh lol  I have to take pic with my phone....

**Comment by WerWolv** [comment]
Fixed with latest release
