### ISSUE TITLE
AMS Crash while in Edizon overlay, Marvel UA3, Docked

### ISSUE THREAD

**Issue by lovelydumpling** [WerWolv/Tesla-Menu#20]
nx-ovlloader 1.0.6
EdiZon overlay 1.1.0

Not sure if issues are best posted on nx-ovlloader or here. The Edizon overlay doesn't have its own GH page either, from what I could find.

After just a few seconds into opening the Edizon menu while playing Marvel Ultimate Alliance 3, docked, atmosphere crashes, like below. No cheats activated. 

Earlier, I was using this extensively with Crash Team Nitro Fueled in Portable Mode perfectly fine, with no crashes. 

Further testing.... 

This crash doesn't happen while on other overlays, just Edizon. It also seems to crash at the _precise_ moment I select (not activate, simply hover over) the [06# P1 Max EP and Inf Special] cheat.

I've attached the cheat file, if it might clue in as to why this is causing a crash.

[E853C44FDF18B88F.txt](https://github.com/WerWolv/Tesla-Menu/files/4923498/E853C44FDF18B88F.txt)

The cheat does work perfectly fine when activated through Edizon in Applet Mode as opposed to using the overlay.

![20200714_234657](https://user-images.githubusercontent.com/30986053/87513881-3f3d5200-c62e-11ea-9fd2-d2cffc86b720.jpg)

**Comment by masagrator** [comment]
Delete **#** from any cheat name

**Comment by lovelydumpling** [comment]
> Delete **#** from any cheat name

Done, did not change a thing. However I'll close this issue because silly me didn't realize the Tesla dev and the Edizon dev are one in the same, and that issues for the EdiZon Tesla overlay are being reported to the EdiZon github page.
