### ISSUE TITLE
Not able to boot into Atmosphere 0.18.1 after installed tesla menu

### ISSUE THREAD

**Issue by javastate** [WerWolv/Tesla-Menu#27]
Hi, can someone help me to look into this issue. My atmosphere cfw wont boot if I install tesla menu. I think someone else also experienced the same issue with atmosphere 0.18. Please refer to this link.

https://github.com/Atmosphere-NX/Atmosphere/issues/1374

I installed tesla on a fresh installed Atmosphere 0.18.1. My atmosphere works perfectly fine after fresh install, but as soon as I installed the tesla, it won't be able to boot into atmosphere cfw. I crashes right after showing the Nintendo logo. However, as soon as I removed the tesla folder(atmosphere/contents/420000000007E51A), I can boot into atmosphere cfw just fine.

I followed this tutorial step by step to install the atmosphere:
https://nh-server.github.io/switch-guide/user_guide/emummc/sd_preparation/

I used TegraExplorer.bin to format my sdcard, hekate_ctcaer_5.5.4.bin as the payroad. I did this with my Mac computer.

Any hint to solve this issue would be greatly appreciated.

**Comment by lookye** [comment]
You made the issue in the "wrong" repository. Atmosphere 0.18.0 and 0.18.1 + Tesla works fine for me. Make sure you set up everything correctly. Also if youre using Mac...Fix the archive bit via hekate after you place the files on your sd card.

**Comment by javastate** [comment]
that was it! Fixing the archive bit was the solution. I spent two days couldn't figure the crash. Thanks so much for your help.

**Comment by lookye** [comment]
Then feel free to close the issue.
