### ISSUE TITLE
compatibility with 12.0.0

### ISSUE THREAD

**Issue by myeuropeanPAL** [WerWolv/Tesla-Menu#29]
While booting into EmuNAND with atmosphere 0.19.1 I got a black screen after the atmosphere logo, the nintendo switch logo never appears if there are any folders in atmosphere\contents.

I only had Tesla-Menu and sys-botbase here, after removing these atmosphere is booting into EmuNAND just fine.

**Comment by WerWolv** [comment]
Make sure all your things are up-to-date and that you don't have old files lying around anywhere anymore. It might also be sys-botbase, I remember that having issues before too. As demonstrated here, Tesla works completely fine on 12.0.0 with latest Atmosphere.
![](https://cdn.discordapp.com/attachments/677630688341655572/831480586853548072/20210413_124607.jpg)
