### ISSUE TITLE
Tesla caused system crash ~

### ISSUE THREAD

**Issue by bao3** [WerWolv/Tesla-Menu#3]
I used Tesla Menu + Nx-ovlload in EmuMMC system. System version is 9.10 , Edicon version 3.10 nightly ( version 3.01 could not work correctly )

I could run Tesla-Menu well with other `.ovl` files ,but while I tried to run your EdiZon ovl file , I could find "Cheat" "status" , the sub menu "status" works well . But when I touched "Cheat" , my system crashed , I had to reboot .

I pasted the log file here:

[My Log file in Pastebin](https://pastebin.com/embed_js/fy2K3RM1)

**Comment by WerWolv** [comment]
This apparently happens when there are a lot of cheats loaded. I have to check if it was accidentally fixed with the new libtesla.
Closing because this is not the right repository.
