### ISSUE TITLE
Tesla Menu will not load/open

### ISSUE THREAD

**Issue by Mewthree3** [WerWolv/Tesla-Menu#31]
I'm using the latest Atmosphere through Hekate.
When I press the button combo (L+Dpad down+right stick down), the menu will not load.
I have updated both the menu, and nx-ovlloader.
This is on a handheld.

**Comment by lookye** [comment]
Please show the contents you have in both locations:

atmosphere/contents/
switch/.overlays

**Comment by Mewthree3** [comment]
Certainly!
Here's the overlays
![image](https://user-images.githubusercontent.com/77812141/120652237-6cf0dc80-c434-11eb-9df4-66e5aca125e1.png)
Here's the contents
![image](https://user-images.githubusercontent.com/77812141/120652308-82fe9d00-c434-11eb-955b-da7c07eec89e.png)

**Comment by WerWolv** [comment]
> `.DS_Store`

Unset archive bits using Hekate

**Comment by Mewthree3** [comment]
Hekate didn’t unset any bits, so the error still persists.

**Comment by Mewthree3** [comment]
Would deleting any .DS-Store files solve the problem?

**Comment by Mewthree3** [comment]
Multiple sources had told me that the menu combo was L+D-pad down+R3. Turns out it was L+D-pad left+X. Apologies, you can close this now!
