### ISSUE TITLE
Not Launching In-Game while docked

### ISSUE THREAD

**Issue by eight85** [WerWolv/Tesla-Menu#35]
Nintendo Switch Erista Model 
Atmosphere 0.19.5 w/ FW 12.1.0 EmuNAND
hekate v5.5.8 & Nyx v1.0.5

Menu works just fine with handheld mode using the joycons and offical Pro Controller. Once docked in-game does not work but works on Horizon interface just fine. I made sure to have all the latest files and rebooting does not solve the issue. Tried launching multiple titles that are digital and physical.

**Comment by lookye** [comment]
Go under Settings -> TV Output and make sure that the display scaling is set to 100%. Anything else will cause the menu to not appear anymore in games.
