### ISSUE TITLE
Tesla Menu Menu disappears in 1.0.2.

### ISSUE THREAD

**Issue by MythraUwU** [WerWolv/Tesla-Menu#4]
Sorry for the inconvenience and my bad English, maybe it's me that I'm not using this well, but when updating Tesla-Menu to 1.0.2 the controls don't work well, the menu is displayed correctly but when entering an option in Edizon (for exemple), Tesla-Menu disappears (the error happens both outside a game and inside). I'm  in Atmosphere 0.10.2, firmware 9.1 and I use EmuMMC.

Thank you.

**Comment by Heartbeat-Heartbreak** [comment]
Same here, I tried the vanilla atmosphere, it still didnt works.
Now I turn back to the previous version, it works well.

**Comment by WerWolv** [comment]
This is because the latest libtesla update was kind of a breaking one. All overlays need to be recompiled with the latest release. I updated the Tesla-Menu, ovlSysmodules and ovlEdiZon but if you use different ones than those, ask their devs to update!
