### ISSUE TITLE
Hello, I found the following two files in my integration package. Although it is not very clear, if it is in the saltysd directory, golden finger will not be able to run and read

### ISSUE THREAD

**Issue by Ic-any** [WerWolv/Tesla-Menu#42]
![MEJ17Q2%UH_J YR~X(1VY4L](https://user-images.githubusercontent.com/92638461/149365709-4f88ec52-6242-44f6-a384-be176f840714.png)
As shown in the figure above, these two files are saltysd_ core. Elf and saltysd_ core. Log, one is the operation log, the other is not clear, but as long as these two files are in the saltysd directory, golden finger will not be able to read.For example, in my Nintendo first-party game animal crossing: new horizons, I run Tesla plug-in and use Tesla's built-in golden finger plug-in, but I can't read and run it.
But I deleted these two files to read and run Tesla golden finger.I've been thinking about this question for a long time. I'd like to ask you. I hope you can adopt it.

**Comment by Ic-any** [comment]
This file is a configuration file about Tesla. But this method is really amazing

**Comment by masagrator** [comment]
This is not an issue with Tesla, so I don't understand why are you trying to force Tesla to delete crucial SaltyNX files when there are overlays using it?  Stop using SaltyNX if it's bothering you.

**Comment by Ic-any** [comment]
This problem has been solved, but two files have been deleted to use Tesla's golden finger. This content has video verification. This method was found in 91tvg forum, but this is the best solution.

**Comment by masagrator** [comment]
By deleting core you're disabling SaltyNX from working properly. 
So just delete SaltyNX overall...
