### ISSUE TITLE
tesla menu not showing on firmware 14.0 atmosphere 1.3.0. 

### ISSUE THREAD

**Issue by carr654** [WerWolv/Tesla-Menu#44]
hi there, hope you are well. could you please update tesla menu if possible tesla menu no longer works in firmware 14.0 and would love my great overlays back I use. many people having same issue as me since updating to 14.0 firmware so believe it could be the way Nintendo changed their code and stuff under the hood. many thanks

**Comment by lookye** [comment]
Tesla was already tested on Firmware 14.0.0 and latest Atmosphere pre-release. It works fine. Make sure you set up your files correctly. You may deleted the tesla files in atmosphere/contents/.

**Comment by carr654** [comment]
yeah i did exactly that by mistake thank you
