### ISSUE TITLE
Tesla doesn't get enabled on boot FW 15

### ISSUE THREAD

**Issue by Lumince** [WerWolv/Tesla-Menu#47]
With just stock Atmosphere, and tesla on my sd card. Tesla will not work with the combo.
Investigating it further, I tried enabling Tesla with a sysmodule toolbox and it works after its manually turned on.
Not really sure whats going on since others have said that it works fine on their systems with the same sd card files....

This is a OLED unit on latest AMS with 15.0.0

**Comment by keso-12** [comment]
I have the same issue, havent tried tesla before but I'm on 15.0.0 and couldnt get it to open.

**Comment by Masamune3210** [comment]
Maybe missing the boot flag file?

**Comment by dorabansde** [comment]
한국사람입니다. 한국어로 보내요

2022년 10월 18일 (화) 오후 9:44, Masamune3210 ***@***.***>님이 작성:

**Comment by Uhhhhnnfall** [comment]
Same problem here

**Comment by funregis** [comment]
Hi can you please uodate tesla to last firmware?

**Comment by keso-12** [comment]
> Hi can you please uodate tesla to last firmware?

I'm already using latest, also did a fresh install since I installed it after I updated to 15.0

I don't know what the boot flag file is though, so not sure if I'm missing that.

**Comment by WerWolv** [comment]
Idk what you people are doing but it works fine on the latest version.
Make sure you have a `boot2.flag` file in the Tesla directory (`/atmosphere/contents/42000...7E51A/flags/boot2.flag`). If that file isn't there, Atmosphere will not start Tesla on boot.
