### ISSUE TITLE
[Hotfix] - Tesla Menu never popup on Hekate 5.9.0 + AMS 1.4.0 + CFW 15.0.1

### ISSUE THREAD

**Issue by MrCanan** [WerWolv/Tesla-Menu#48]
Hi,

I use all lastest version from official WerWolv github :
- nx-ovlloader (folder "420000000007E51A" in "/atmosphere/contents/" folder)
- Tesla Menu ("ovlmenu.ovl" file in "/switch/.overlays/" folder)
- EdiZon ("EdiZon.nro" file in "/switch/" folder)
- EdiZon overlay ("ovlmenu.ovl" file in "/switch/.overlays/" folder)
- EdiZon overlay alternative from proferabg for "HOS 15 Full Support" ("ovlmenu.ovl" file in "/switch/.overlays/" folder)

Tesla Menu and Edizon overlay worked fine before I update to lastest Hekate 5.9.0, AMS 1.4.0 and CFW 15.0.1
> Now, it simply si nothing, so no more overlay...

I try also to remove EdiZon overlay to have nothing to impact Tesla Menu ("ovlmenu.ovl" file in "/switch/.overlays/" folder), but same problem again.

I try to change the shortcut "key_combo" in the config ("config.ini" file in "/config/testla/" folder), but same problem.
> So I let by default : key_combo=L+DDOWN+RS

I try exactly the same on my second switch, again the same issue.

Any idea and or help ?

Thank you on advance,
Best regards

**Comment by deejay87** [comment]
Hi , i have test and no problem for me to change the combo on config.ini on ams 1.4.0 | 15.0.1

**Comment by MrCanan** [comment]
Hi deejay87,

The error is not to change the combo...

> The menu never open after update AMS and CFW

**Comment by deejay87** [comment]
Ok but i don't have problem to open, you are shure you have install all files ? (do this on hekate usb and start atmosphere)
"atmosphere\contents\420000000007E51A\"

**Comment by Herya** [comment]
Hi,

Same issue on my side, any idea if there will be a fix please ?

**Comment by mushishi06** [comment]
Hi,

I came across this issue after getting the same thing as @MrCanan .

After reading the above comments, I double check all my files and setting ang got the same as him.
I try the same thing and still no change no popup is showing :(

Any advise/solution to try to make it work again wil be great.
thx
