### ISSUE TITLE
Tesala Menu Disappears in 1.0.2

### ISSUE THREAD

**Issue by assassins7777** [WerWolv/Tesla-Menu#5]
The same here, having updated to the latest version of tesla and having Atmosphere in the latest version when choosing EdiZon to use the Cheats Codes either in or out of the game the Menu-Tesla disappears and the controls do not respond quite well.
Thanks in advance.

**Comment by muxi1** [comment]
I can confirm that. Only the second time the menu is called up, a selection is possible.

**Comment by WerWolv** [comment]
This happens if you use old overlays in combination with new tesla menu or vice-versa. Update both.
