### ISSUE TITLE
Tesla menu fix for 16.0.0 atmosphere 1.5.1

### ISSUE THREAD

**Issue by andrea-ap** [WerWolv/Tesla-Menu#55]
Tesla menu fix for 16.0.0 atmosphere 1.5.1 not works

**Comment by chrisssj2** [comment]
It softlocks my switch when going into the menu a few times very annoying

**Comment by ThePBone** [comment]
You need to update all the .ovl files in /switch/overlays with new versions that have proper 16.0.0 support and are compiled with the latest version of libtesla.
Old .ovl files are not compatible and will softlock the switch.
