### ISSUE TITLE
When I download the 16.0 release i cant open my hb menu through applet

### ISSUE THREAD

**Issue by zackrage123** [WerWolv/Tesla-Menu#58]

**Comment by zackrage123** [comment]
When I download the 16.0 release I cant open my homebrew menu through applet but when I 
take tesla menu off my SD card it works just fine

**Comment by masagrator** [comment]
Try to delete everything except nx-ovlloader and check again. This sounds like you have too much sysmodules installed, not exactly Tesla's fault.

**Comment by zackrage123** [comment]
ok
