### ISSUE TITLE
Atmosphere 16.0.2. emuiibo 0.6.5. Tesla 1.2.1. nx-ovlloader 1.0.6.  I had this problem.

### ISSUE THREAD

**Issue by JieZhangCoder** [WerWolv/Tesla-Menu#63]
![344766214_995350741455509_4792352551219846502_n](https://user-images.githubusercontent.com/132520433/236062758-cd8e9d47-5a44-4896-85f9-01359f25665f.jpg)
one guy say it  isn’t even about emuiibo, it’s about Tesla menu.
https://github.com/XorTroll/emuiibo/issues/236#issuecomment-1534214559

**Comment by masagrator** [comment]
If it's about Tesla menu, then download it from here (ovlmenu)

https://gbatemp.net/threads/tesla-the-nintendo-switch-overlay-menu.557362/page-72#post-10121629

**Comment by LayKii98** [comment]
> If it's about Tesla menu, then download it from here (ovlmenu)
> 
> https://gbatemp.net/threads/tesla-the-nintendo-switch-overlay-menu.557362/page-72#post-10121629

Can you send a direct link to the download please? for some reason, the page does not want to load me

**Comment by newwaverap** [comment]
Does anyone have a solution? I am also getting a crash immediately after launching Emuiibo from the Tesla menu but Edizon runs fine.

**Comment by JohanGPI** [comment]
Try to look for any .ovl file in the root of your sd card, if there is one move it into switch/.overlays that fixed for me

**Comment by JieZhangCoder** [comment]
It is the problem of emuiibo，use the latest release.
