### ISSUE TITLE
[Possible Bug Report] Tesla Menu Present, But Invisible, While Docked

### ISSUE THREAD

**Issue by ToxiClay** [WerWolv/Tesla-Menu#64]
With the understanding that I might be *mis*-understanding something about how Tesla is designed to work, I think I'm running into an issue.

With the Switch in handheld mode, I can invoke Tesla using L+Down+R3 from both the Home screen and from within an app.

With the Switch docked, however, I lose the ability to invoke Tesla from the app; I can only do so from the home screen. Further, if I invoke Tesla while handheld and then immediately dock the Switch, the overlay menu is not visible when the TV kicks on.

Whoops, important information: nx-ovlloader 1.0.6-13295c6

**Comment by ToxiClay** [comment]
Anecdotally, it appears that the overlay is firing while docked, but it's just invisible -- the game stopped responding to my input until I B'd out of what I assume was the overlay actually being present.

**Comment by Masamune3210** [comment]
Make sure your TV scaling in the switch's settings is set to 100%. Tesla doesn't show if it's set any lower.

**Comment by ToxiClay** [comment]
Good catch! I can confirm that my scaling settings were at 96%, and resetting that to 100% did in fact cause Tesla to pop back.

What's weird, though, is that 96% is the correct setting to make the arrows line up perfectly with my TV; this is more than a little distressing. So now I have to choose between seeing all of the game and having access to the overlay; joy.
