### ISSUE TITLE
Just press L + D-Pad-Down to run it.

### ISSUE THREAD

**Issue by hoonythink** [WerWolv/Tesla-Menu#67]
I am using it well. thank you first.

I have a question, so please ask.
My SWTICH is no need to press the R stick to run tesla-munu.
Just press L + D-Pad-Down to run it.
It's embarrassing because it's so easy to do.
How can I change it? (L + D-Pad-Down + R-stick)

My switch version..
-Switch firmware : v16.0.3
-Atmosphere : v1.5.3
-Nx-ovlloader : v1.0.7
-tesla-menu : v1.2.3 

thank you again.

**Comment by crunchysoft** [comment]
I have the same issue on my switch.
I've updated the config file (~/config/tesla/config.ini) as seen below, but it still activates with only **L + D-Pad-Down**, rather than **L + D-Pad-Down + R3** as I would prefer.

```
[tesla]
key_combo=L+DDOWN+R3
```

**Comment by crunchysoft** [comment]
Just an update. I tested using a different 3rd button (other than R3) and it worked as expected, so this appears to be an issue with mapping the sticks.

Working config:
```
[tesla]
key_combo=L+DDOWN+ZR
```

**Comment by hoonythink** [comment]
thank you.
my switch work it.

**Comment by gczark** [comment]
anybody know how to use capture or home button?

**Comment by masagrator** [comment]
You can't because they are special buttons not captured by pad. It's possible to listen to home button event though, but that's not supported by tesla as this event is used to hide tesla.

**Comment by hippydave** [comment]
This is still an issue, with the default L+DDOWN+R3 trigger configured, it opens with only L and d-pad down pressed. Is there any solution to this, besides using a workaround of different buttons? Thanks
