### ISSUE TITLE
Tesla menu not responding to button combination

### ISSUE THREAD

**Issue by ToxiClay** [WerWolv/Tesla-Menu#68]
On `16.1.0|AMS 1.5.5|S`, pressing the button combination L+D-Down+R3 no longer invokes the Tesla menu; on `15.0.1|AMS 1.5.5|E`, it does.

It's the same SD card with the same file contents, so the only difference is the HOS version.

Additionally, this is in handheld mode so there's no scaling concern.

**Comment by anggarasaja** [comment]
Mine also 16.1.0|AMS 1.5.5|S, overlay is not working in game but works on home menu.

**Comment by ToxiClay** [comment]
Hmm. It doesn't even work on the home screen for me.

**Comment by bachato** [comment]
I'm on `16.1.0|AMS 1.5.5|E`, the button combination doesn't work for me either, in game mor on the  home menu.

**Comment by ToxiClay** [comment]
Well...now it is working, and I'm not entirely sure why. I don't think I changed anything, other than maybe I swapped out a misbehaving sys-clk sysmodule somewhere? Wild. It's functioning in-game, as well.

![2023101414084700-57B4628D2267231D57E0FC1078C0596D](https://github.com/WerWolv/Tesla-Menu/assets/13796683/bd6e8e1e-c791-44d3-ba63-f0330aa08dec)
