### ISSUE TITLE
Error: 2168-0000 - happens sometimes after reboot.

### ISSUE THREAD

**Issue by s0t7x** [WerWolv/Tesla-Menu#7]
After a reboot, using Tesla had caused a crash whenever I was trying to load any overlay.
It always was 2168-0000. I could not find any real information on this error.
I literally did nothing to the switch or files!

May it is my exFat, that fucks everything up sometimes.

Replacing the .overlays/ovlmenu.ovl with a new one instantly fixed it.
Could not reproduce error so far.

Just wanted to let u know!

**Comment by WerWolv** [comment]
This is 100% Nintendo's exFAT drivers corrupting your SD card. Format it to FAT32.

2168-0000 means `Userland ARM undefined instruction exception`, it tried to execute an instruction it did not recognize (because the file was corrupted)
