### ISSUE TITLE
Tesla Will Not Appear On Scaled Screen Sizes

### ISSUE THREAD

**Issue by phnord** [WerWolv/Tesla-Menu#70]
If the setting on the switch in System Settings -> TV Output -> Adjust Screen Size is set to anything other than 100%, the Tesla Overlays will not appear.

Please fix this.  Like many other users, if my screen size is set to 100%, the edges are clipped.  I would like to still be able to use Tesla.

Thanks.

**Comment by masagrator** [comment]
https://github.com/WerWolv/Tesla-Menu/issues/53

There is no need for 2 the same issues.
