### ISSUE TITLE
Built from most recent code lead to a crash

### ISSUE THREAD

**Issue by impeeza** [WerWolv/Tesla-Menu#71]
Hello there.

First at all @zdm65477730 thanks a lot for all your great Work, I am using the latest Tesla SYSMODULE NX-OVLLoader built from https://github.com/zdm65477730/nx-ovlloader, with latest LibNX.

After built the most recent Tesla-Menu from https://github.com/zdm65477730/Tesla-Menu successfully:
![image](https://github.com/user-attachments/assets/2e0db309-ee9c-4c05-b9cc-660dd0a6417f)

Trying to boot my console I get this error:

![image](https://github.com/user-attachments/assets/0b707421-16f5-40f4-9c10-b19ae815cc01)

![image](https://github.com/user-attachments/assets/8d73f316-9257-4394-813c-3120df014f94)

Am I missing something?

**Comment by WerWolv** [comment]
Complain to the person who maintains that fork lol

**Comment by impeeza** [comment]
Thanks @WerWolv, I tried but the ZDM repo, issues is redirected to this one!  ha ha ha,  thanks again for the quick response.
